"""added users table

Revision ID: 5ad4b786a674
Revises: 2117794f0e81
Create Date: 2023-10-18 16:09:19.201963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad4b786a674'
down_revision: Union[str, None] = '2117794f0e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('restaurants')
    # ### end Alembic commands ###
    
    op.bulk_insert(users,
    [
        {'email':'oliver.giles@lewagon.org','hashed_password':'notreally'},
        {'email':'bruno@lewagon.org','hashed_password':'notreallyeither'}
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey'),
    sa.UniqueConstraint('email', name='restaurants_email_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
