"""added tweets table

Revision ID: 76617ec0a2f4
Revises: 070e5a9aa0db
Create Date: 2023-10-18 17:30:27.951210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76617ec0a2f4'
down_revision: Union[str, None] = '070e5a9aa0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
